# travis build for APhotoManager
language: android
android:
  components:
    # https://github.com/travis-ci/travis-ci/issues/5036
    - tools
    - build-tools-23.0.2
    - android-21
    - add-on
    - extra

before_install:
# http://stackoverflow.com/questions/33820638/travis-yml-gradlew-permission-denied
 - chmod +x gradlew
 
 
script:
  # error "Gradle Test Executor 137" Process 'Gradle Test Executor 1' finished with non-zero exit value 137
  # This usually indicates a SIGKILL being issued by TravisCI due to high memory use or a build taking too long. https://discuss.gradle.org/t/gradle-travis-ci/11928
  - ./gradlew assemble pixymeta-j2se-demo:runFatJar pixymeta-ext-lib:test pixymeta-ext-lib:jacocoTestReport
  - ls -l pixymeta-j2se-demo/build/testresults/

after_success:
  - bash <(curl -s https://codecov.io/bash)
  